package exception1;

public class Throw_Ex2_Test {
	public void input() throws ArithmeticException
	{
		int hap=99;
		int num=0;
		int avg=hap/num;
		System.out.println(avg);
	}

}
